//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintManager.MainClient.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PrintManager.MainClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AnalogView_TextBlock_01 {
            get {
                return ResourceManager.GetString("AnalogView_TextBlock_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AnalogView_TextBlock_02 {
            get {
                return ResourceManager.GetString("AnalogView_TextBlock_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AnalogView_TextBlock_03 {
            get {
                return ResourceManager.GetString("AnalogView_TextBlock_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AnalogView_TextBlock_04 {
            get {
                return ResourceManager.GetString("AnalogView_TextBlock_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AnalogView_TextBlock_05 {
            get {
                return ResourceManager.GetString("AnalogView_TextBlock_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AnalogView_TextBlock_06 {
            get {
                return ResourceManager.GetString("AnalogView_TextBlock_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AnalogView_TextBlock_07 {
            get {
                return ResourceManager.GetString("AnalogView_TextBlock_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AnalogView_TextBlock_08 {
            get {
                return ResourceManager.GetString("AnalogView_TextBlock_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AnalogView_TextBlock_09 {
            get {
                return ResourceManager.GetString("AnalogView_TextBlock_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AnalogView_TextBlock_10 {
            get {
                return ResourceManager.GetString("AnalogView_TextBlock_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AnalogView_TextBlock_11 {
            get {
                return ResourceManager.GetString("AnalogView_TextBlock_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AnalogView_TextBlock_12 {
            get {
                return ResourceManager.GetString("AnalogView_TextBlock_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AnalogView_TextBlock_13 {
            get {
                return ResourceManager.GetString("AnalogView_TextBlock_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AnalogView_TextBlock_14 {
            get {
                return ResourceManager.GetString("AnalogView_TextBlock_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AnalogView_TextBlock_15 {
            get {
                return ResourceManager.GetString("AnalogView_TextBlock_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AnalogView_TextBlock_16 {
            get {
                return ResourceManager.GetString("AnalogView_TextBlock_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AnalogView_TextBlock_17 {
            get {
                return ResourceManager.GetString("AnalogView_TextBlock_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AnalogView_TextBlock_18 {
            get {
                return ResourceManager.GetString("AnalogView_TextBlock_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AnalogView_TextBlock_19 {
            get {
                return ResourceManager.GetString("AnalogView_TextBlock_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AnalogView_TextBlock_20 {
            get {
                return ResourceManager.GetString("AnalogView_TextBlock_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AnalogView_TextBlock_21 {
            get {
                return ResourceManager.GetString("AnalogView_TextBlock_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Dialog_Comm_01 {
            get {
                return ResourceManager.GetString("Dialog_Comm_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Dialog_Comm_02 {
            get {
                return ResourceManager.GetString("Dialog_Comm_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Dialog_Comm_03 {
            get {
                return ResourceManager.GetString("Dialog_Comm_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Dialog_Comm_04 {
            get {
                return ResourceManager.GetString("Dialog_Comm_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EventHistoryLogView_TextBlock_01 {
            get {
                return ResourceManager.GetString("EventHistoryLogView_TextBlock_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EventHistoryLogView_TextBlock_02 {
            get {
                return ResourceManager.GetString("EventHistoryLogView_TextBlock_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EventHistoryLogView_TextBlock_03 {
            get {
                return ResourceManager.GetString("EventHistoryLogView_TextBlock_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EventHistoryLogView_TextBlock_04 {
            get {
                return ResourceManager.GetString("EventHistoryLogView_TextBlock_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EventHistoryLogView_TextBlock_05 {
            get {
                return ResourceManager.GetString("EventHistoryLogView_TextBlock_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EventHistoryLogView_TextBlock_06 {
            get {
                return ResourceManager.GetString("EventHistoryLogView_TextBlock_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EventHistoryLogView_TextBlock_07 {
            get {
                return ResourceManager.GetString("EventHistoryLogView_TextBlock_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EventHistoryLogView_TextBlock_08 {
            get {
                return ResourceManager.GetString("EventHistoryLogView_TextBlock_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EventHistoryLogView_TextBlock_09 {
            get {
                return ResourceManager.GetString("EventHistoryLogView_TextBlock_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EventHistoryLogView_TextBlock_10 {
            get {
                return ResourceManager.GetString("EventHistoryLogView_TextBlock_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EventHistoryLogView_TextBlock_11 {
            get {
                return ResourceManager.GetString("EventHistoryLogView_TextBlock_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EventHistoryLogView_TextBlock_12 {
            get {
                return ResourceManager.GetString("EventHistoryLogView_TextBlock_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EventHistoryLogView_TextBlock_13 {
            get {
                return ResourceManager.GetString("EventHistoryLogView_TextBlock_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EventLogView_TextBlock_01 {
            get {
                return ResourceManager.GetString("EventLogView_TextBlock_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EventLogView_TextBlock_02 {
            get {
                return ResourceManager.GetString("EventLogView_TextBlock_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EventLogView_TextBlock_03 {
            get {
                return ResourceManager.GetString("EventLogView_TextBlock_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EventLogView_TextBlock_04 {
            get {
                return ResourceManager.GetString("EventLogView_TextBlock_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EventLogView_TextBlock_05 {
            get {
                return ResourceManager.GetString("EventLogView_TextBlock_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EventLogView_TextBlock_06 {
            get {
                return ResourceManager.GetString("EventLogView_TextBlock_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EventLogView_TextBlock_07 {
            get {
                return ResourceManager.GetString("EventLogView_TextBlock_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string HistoryLogView_TextBlock_01 {
            get {
                return ResourceManager.GetString("HistoryLogView_TextBlock_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string HistoryLogView_TextBlock_02 {
            get {
                return ResourceManager.GetString("HistoryLogView_TextBlock_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string HistoryLogView_TextBlock_03 {
            get {
                return ResourceManager.GetString("HistoryLogView_TextBlock_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string HistoryLogView_TextBlock_04 {
            get {
                return ResourceManager.GetString("HistoryLogView_TextBlock_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string HistoryLogView_TextBlock_05 {
            get {
                return ResourceManager.GetString("HistoryLogView_TextBlock_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string HistoryLogView_TextBlock_06 {
            get {
                return ResourceManager.GetString("HistoryLogView_TextBlock_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string HistoryLogView_TextBlock_07 {
            get {
                return ResourceManager.GetString("HistoryLogView_TextBlock_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string HistoryLogView_TextBlock_08 {
            get {
                return ResourceManager.GetString("HistoryLogView_TextBlock_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string HistoryLogView_TextBlock_09 {
            get {
                return ResourceManager.GetString("HistoryLogView_TextBlock_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string HistoryLogView_TextBlock_10 {
            get {
                return ResourceManager.GetString("HistoryLogView_TextBlock_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string HistoryLogView_TextBlock_11 {
            get {
                return ResourceManager.GetString("HistoryLogView_TextBlock_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string HomeView_TextBlock_01 {
            get {
                return ResourceManager.GetString("HomeView_TextBlock_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string HomeView_TextBlock_02 {
            get {
                return ResourceManager.GetString("HomeView_TextBlock_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string HomeView_TextBlock_03 {
            get {
                return ResourceManager.GetString("HomeView_TextBlock_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string HomeView_TextBlock_04 {
            get {
                return ResourceManager.GetString("HomeView_TextBlock_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string HomeView_TextBlock_05 {
            get {
                return ResourceManager.GetString("HomeView_TextBlock_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string HomeView_TextBlock_06 {
            get {
                return ResourceManager.GetString("HomeView_TextBlock_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string HomeView_TextBlock_07 {
            get {
                return ResourceManager.GetString("HomeView_TextBlock_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string HomeView_TextBlock_08 {
            get {
                return ResourceManager.GetString("HomeView_TextBlock_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string HomeView_TextBlock_09 {
            get {
                return ResourceManager.GetString("HomeView_TextBlock_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string HomeView_TextBlock_10 {
            get {
                return ResourceManager.GetString("HomeView_TextBlock_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string HomeView_TextBlock_11 {
            get {
                return ResourceManager.GetString("HomeView_TextBlock_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string HomeView_TextBlock_12 {
            get {
                return ResourceManager.GetString("HomeView_TextBlock_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LanguageView_TextBlock_01 {
            get {
                return ResourceManager.GetString("LanguageView_TextBlock_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LanguageView_TextBlock_02 {
            get {
                return ResourceManager.GetString("LanguageView_TextBlock_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LanguageView_TextBlock_03 {
            get {
                return ResourceManager.GetString("LanguageView_TextBlock_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LanguageView_TextBlock_04 {
            get {
                return ResourceManager.GetString("LanguageView_TextBlock_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LanguageView_TextBlock_05 {
            get {
                return ResourceManager.GetString("LanguageView_TextBlock_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LanguageView_TextBlock_06 {
            get {
                return ResourceManager.GetString("LanguageView_TextBlock_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LanguageView_TextBlock_07 {
            get {
                return ResourceManager.GetString("LanguageView_TextBlock_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LanguageView_TextBlock_08 {
            get {
                return ResourceManager.GetString("LanguageView_TextBlock_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LanguageView_TextBlock_09 {
            get {
                return ResourceManager.GetString("LanguageView_TextBlock_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LanguageView_TextBlock_10 {
            get {
                return ResourceManager.GetString("LanguageView_TextBlock_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LoginView_TextBlock_01 {
            get {
                return ResourceManager.GetString("LoginView_TextBlock_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LoginView_TextBlock_02 {
            get {
                return ResourceManager.GetString("LoginView_TextBlock_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LoginView_TextBlock_03 {
            get {
                return ResourceManager.GetString("LoginView_TextBlock_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LogView_TextBlock_01 {
            get {
                return ResourceManager.GetString("LogView_TextBlock_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LogView_TextBlock_02 {
            get {
                return ResourceManager.GetString("LogView_TextBlock_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LogView_TextBlock_03 {
            get {
                return ResourceManager.GetString("LogView_TextBlock_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LogView_TextBlock_04 {
            get {
                return ResourceManager.GetString("LogView_TextBlock_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LogView_TextBlock_05 {
            get {
                return ResourceManager.GetString("LogView_TextBlock_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PagePicker_TextBlock_01 {
            get {
                return ResourceManager.GetString("PagePicker_TextBlock_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PagePicker_TextBlock_02 {
            get {
                return ResourceManager.GetString("PagePicker_TextBlock_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PagePicker_TextBlock_03 {
            get {
                return ResourceManager.GetString("PagePicker_TextBlock_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PagePicker_TextBlock_04 {
            get {
                return ResourceManager.GetString("PagePicker_TextBlock_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ParModifyView_TextBlock_01 {
            get {
                return ResourceManager.GetString("ParModifyView_TextBlock_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ParModifyView_TextBlock_02 {
            get {
                return ResourceManager.GetString("ParModifyView_TextBlock_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ParModifyView_TextBlock_03 {
            get {
                return ResourceManager.GetString("ParModifyView_TextBlock_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ParModifyView_TextBlock_04 {
            get {
                return ResourceManager.GetString("ParModifyView_TextBlock_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ParModifyView_TextBlock_05 {
            get {
                return ResourceManager.GetString("ParModifyView_TextBlock_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ParModifyView_TextBlock_06 {
            get {
                return ResourceManager.GetString("ParModifyView_TextBlock_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ParModifyView_TextBlock_07 {
            get {
                return ResourceManager.GetString("ParModifyView_TextBlock_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ParModifyView_TextBlock_08 {
            get {
                return ResourceManager.GetString("ParModifyView_TextBlock_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ParModifyView_TextBlock_09 {
            get {
                return ResourceManager.GetString("ParModifyView_TextBlock_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ParModifyView_TextBlock_10 {
            get {
                return ResourceManager.GetString("ParModifyView_TextBlock_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ParModifyView_TextBlock_11 {
            get {
                return ResourceManager.GetString("ParModifyView_TextBlock_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ParModifyView_TextBlock_12 {
            get {
                return ResourceManager.GetString("ParModifyView_TextBlock_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ParModifyView_TextBlock_13 {
            get {
                return ResourceManager.GetString("ParModifyView_TextBlock_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ParUpdateTemp1View_TextBlock_01 {
            get {
                return ResourceManager.GetString("ParUpdateTemp1View_TextBlock_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ParUpdateTemp1View_TextBlock_02 {
            get {
                return ResourceManager.GetString("ParUpdateTemp1View_TextBlock_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ParUpdateTemp1View_TextBlock_03 {
            get {
                return ResourceManager.GetString("ParUpdateTemp1View_TextBlock_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ParUpdateTemp1View_TextBlock_04 {
            get {
                return ResourceManager.GetString("ParUpdateTemp1View_TextBlock_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ParUpdateTemp1View_TextBlock_05 {
            get {
                return ResourceManager.GetString("ParUpdateTemp1View_TextBlock_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ParUpdateTemp1View_TextBlock_06 {
            get {
                return ResourceManager.GetString("ParUpdateTemp1View_TextBlock_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ParUpdateTemp1View_TextBlock_07 {
            get {
                return ResourceManager.GetString("ParUpdateTemp1View_TextBlock_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ParUpdateTemp1View_TextBlock_08 {
            get {
                return ResourceManager.GetString("ParUpdateTemp1View_TextBlock_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ParUpdateTemp2View_TextBlock_01 {
            get {
                return ResourceManager.GetString("ParUpdateTemp2View_TextBlock_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ParUpdateTemp2View_TextBlock_02 {
            get {
                return ResourceManager.GetString("ParUpdateTemp2View_TextBlock_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ParUpdateTemp2View_TextBlock_03 {
            get {
                return ResourceManager.GetString("ParUpdateTemp2View_TextBlock_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ParUpdateTemp2View_TextBlock_04 {
            get {
                return ResourceManager.GetString("ParUpdateTemp2View_TextBlock_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ParUpdateTemp2View_TextBlock_05 {
            get {
                return ResourceManager.GetString("ParUpdateTemp2View_TextBlock_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ParUpdateTemp2View_TextBlock_06 {
            get {
                return ResourceManager.GetString("ParUpdateTemp2View_TextBlock_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ParUpdateTemp2View_TextBlock_07 {
            get {
                return ResourceManager.GetString("ParUpdateTemp2View_TextBlock_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ParUpdateTemp2View_TextBlock_08 {
            get {
                return ResourceManager.GetString("ParUpdateTemp2View_TextBlock_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ParUpdateTemp2View_TextBlock_09 {
            get {
                return ResourceManager.GetString("ParUpdateTemp2View_TextBlock_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ParUpdateTemp2View_TextBlock_10 {
            get {
                return ResourceManager.GetString("ParUpdateTemp2View_TextBlock_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ParUpdateTemp2View_TextBlock_11 {
            get {
                return ResourceManager.GetString("ParUpdateTemp2View_TextBlock_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ParUpdateTemp2View_TextBlock_12 {
            get {
                return ResourceManager.GetString("ParUpdateTemp2View_TextBlock_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ParUpdateTemp2View_TextBlock_13 {
            get {
                return ResourceManager.GetString("ParUpdateTemp2View_TextBlock_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ParUpdateTemp2View_TextBlock_14 {
            get {
                return ResourceManager.GetString("ParUpdateTemp2View_TextBlock_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ParUpdateTemp2View_TextBlock_15 {
            get {
                return ResourceManager.GetString("ParUpdateTemp2View_TextBlock_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ParUpdateTemp2View_TextBlock_16 {
            get {
                return ResourceManager.GetString("ParUpdateTemp2View_TextBlock_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ParUpdateTemp2View_TextBlock_17 {
            get {
                return ResourceManager.GetString("ParUpdateTemp2View_TextBlock_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ParUpdateTemp3View_TextBlock_01 {
            get {
                return ResourceManager.GetString("ParUpdateTemp3View_TextBlock_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ParUpdateTemp3View_TextBlock_02 {
            get {
                return ResourceManager.GetString("ParUpdateTemp3View_TextBlock_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ParUpdateTemp3View_TextBlock_03 {
            get {
                return ResourceManager.GetString("ParUpdateTemp3View_TextBlock_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ParUpdateTemp3View_TextBlock_04 {
            get {
                return ResourceManager.GetString("ParUpdateTemp3View_TextBlock_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ParUpdateTemp3View_TextBlock_05 {
            get {
                return ResourceManager.GetString("ParUpdateTemp3View_TextBlock_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ParUpdateTemp3View_TextBlock_06 {
            get {
                return ResourceManager.GetString("ParUpdateTemp3View_TextBlock_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ParUpdateTemp4View_TextBlock_01 {
            get {
                return ResourceManager.GetString("ParUpdateTemp4View_TextBlock_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ParUpdateTemp4View_TextBlock_02 {
            get {
                return ResourceManager.GetString("ParUpdateTemp4View_TextBlock_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ParUpdateTemp4View_TextBlock_03 {
            get {
                return ResourceManager.GetString("ParUpdateTemp4View_TextBlock_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ParUpdateTemp4View_TextBlock_04 {
            get {
                return ResourceManager.GetString("ParUpdateTemp4View_TextBlock_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ProductView_TextBlock_01 {
            get {
                return ResourceManager.GetString("ProductView_TextBlock_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ProductView_TextBlock_02 {
            get {
                return ResourceManager.GetString("ProductView_TextBlock_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ProductView_TextBlock_03 {
            get {
                return ResourceManager.GetString("ProductView_TextBlock_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ProductView_TextBlock_04 {
            get {
                return ResourceManager.GetString("ProductView_TextBlock_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ProductView_TextBlock_05 {
            get {
                return ResourceManager.GetString("ProductView_TextBlock_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ProductView_TextBlock_06 {
            get {
                return ResourceManager.GetString("ProductView_TextBlock_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ProductView_TextBlock_07 {
            get {
                return ResourceManager.GetString("ProductView_TextBlock_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ProductView_TextBlock_08 {
            get {
                return ResourceManager.GetString("ProductView_TextBlock_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ProductView_TextBlock_09 {
            get {
                return ResourceManager.GetString("ProductView_TextBlock_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ProductView_TextBlock_10 {
            get {
                return ResourceManager.GetString("ProductView_TextBlock_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ProductView_TextBlock_11 {
            get {
                return ResourceManager.GetString("ProductView_TextBlock_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ProductView_TextBlock_12 {
            get {
                return ResourceManager.GetString("ProductView_TextBlock_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ProductView_TextBlock_13 {
            get {
                return ResourceManager.GetString("ProductView_TextBlock_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ProductView_TextBlock_14 {
            get {
                return ResourceManager.GetString("ProductView_TextBlock_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ProductView_TextBlock_15 {
            get {
                return ResourceManager.GetString("ProductView_TextBlock_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ProductView_TextBlock_16 {
            get {
                return ResourceManager.GetString("ProductView_TextBlock_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ProductView_TextBlock_17 {
            get {
                return ResourceManager.GetString("ProductView_TextBlock_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ShellView_TextBlock_01 {
            get {
                return ResourceManager.GetString("ShellView_TextBlock_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ShellView_TextBlock_02 {
            get {
                return ResourceManager.GetString("ShellView_TextBlock_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ShellView_TextBlock_03 {
            get {
                return ResourceManager.GetString("ShellView_TextBlock_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ShellView_TextBlock_04 {
            get {
                return ResourceManager.GetString("ShellView_TextBlock_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ShellView_TextBlock_05 {
            get {
                return ResourceManager.GetString("ShellView_TextBlock_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ShellView_TextBlock_06 {
            get {
                return ResourceManager.GetString("ShellView_TextBlock_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ShellView_TextBlock_07 {
            get {
                return ResourceManager.GetString("ShellView_TextBlock_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ShellView_TextBlock_08 {
            get {
                return ResourceManager.GetString("ShellView_TextBlock_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ShellView_TextBlock_09 {
            get {
                return ResourceManager.GetString("ShellView_TextBlock_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ShellView_TextBlock_10 {
            get {
                return ResourceManager.GetString("ShellView_TextBlock_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ShellView_TextBlock_11 {
            get {
                return ResourceManager.GetString("ShellView_TextBlock_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ShellView_TextBlock_12 {
            get {
                return ResourceManager.GetString("ShellView_TextBlock_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ShellView_TextBlock_13 {
            get {
                return ResourceManager.GetString("ShellView_TextBlock_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ShellView_TextBlock_14 {
            get {
                return ResourceManager.GetString("ShellView_TextBlock_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SystemSettingView_Button_01 {
            get {
                return ResourceManager.GetString("SystemSettingView_Button_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SystemSettingView_Button_02 {
            get {
                return ResourceManager.GetString("SystemSettingView_Button_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SystemSettingView_Button_03 {
            get {
                return ResourceManager.GetString("SystemSettingView_Button_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SystemSettingView_Button_04 {
            get {
                return ResourceManager.GetString("SystemSettingView_Button_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SystemSettingView_Button_05 {
            get {
                return ResourceManager.GetString("SystemSettingView_Button_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SystemSettingView_TextBlock_01 {
            get {
                return ResourceManager.GetString("SystemSettingView_TextBlock_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SystemSettingView_TextBlock_02 {
            get {
                return ResourceManager.GetString("SystemSettingView_TextBlock_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SystemSettingView_TextBlock_03 {
            get {
                return ResourceManager.GetString("SystemSettingView_TextBlock_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SystemSettingView_TextBlock_04 {
            get {
                return ResourceManager.GetString("SystemSettingView_TextBlock_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SystemSettingView_TextBlock_05 {
            get {
                return ResourceManager.GetString("SystemSettingView_TextBlock_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SystemSettingView_TextBlock_06 {
            get {
                return ResourceManager.GetString("SystemSettingView_TextBlock_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SystemSettingView_TextBlock_07 {
            get {
                return ResourceManager.GetString("SystemSettingView_TextBlock_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SystemSettingView_TextBlock_08 {
            get {
                return ResourceManager.GetString("SystemSettingView_TextBlock_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SystemSettingView_TextBlock_09 {
            get {
                return ResourceManager.GetString("SystemSettingView_TextBlock_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SystemSettingView_TextBlock_10 {
            get {
                return ResourceManager.GetString("SystemSettingView_TextBlock_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SystemSettingView_TextBlock_11 {
            get {
                return ResourceManager.GetString("SystemSettingView_TextBlock_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SystemSettingView_TextBlock_12 {
            get {
                return ResourceManager.GetString("SystemSettingView_TextBlock_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TimeProgramView_TextBlock_01 {
            get {
                return ResourceManager.GetString("TimeProgramView_TextBlock_01", resourceCulture);
            }
        }
    }
}
