//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintManager.MainClient.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PrintManager.MainClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string SystemSettingView_Button_01 {
            get {
                return ResourceManager.GetString("SystemSettingView_Button_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string SystemSettingView_Button_02 {
            get {
                return ResourceManager.GetString("SystemSettingView_Button_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to default.
        /// </summary>
        public static string SystemSettingView_Button_03 {
            get {
                return ResourceManager.GetString("SystemSettingView_Button_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SystemSettingView_Button_04 {
            get {
                return ResourceManager.GetString("SystemSettingView_Button_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel!.
        /// </summary>
        public static string SystemSettingView_Button_05 {
            get {
                return ResourceManager.GetString("SystemSettingView_Button_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System configuration.
        /// </summary>
        public static string SystemSettingView_TextBlock_01 {
            get {
                return ResourceManager.GetString("SystemSettingView_TextBlock_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database connection string!.
        /// </summary>
        public static string SystemSettingView_TextBlock_02 {
            get {
                return ResourceManager.GetString("SystemSettingView_TextBlock_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Native IP address!.
        /// </summary>
        public static string SystemSettingView_TextBlock_03 {
            get {
                return ResourceManager.GetString("SystemSettingView_TextBlock_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically connect to the database!.
        /// </summary>
        public static string SystemSettingView_TextBlock_04 {
            get {
                return ResourceManager.GetString("SystemSettingView_TextBlock_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;  Configuration of client.
        /// </summary>
        public static string SystemSettingView_TextBlock_05 {
            get {
                return ResourceManager.GetString("SystemSettingView_TextBlock_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        public static string SystemSettingView_TextBlock_06 {
            get {
                return ResourceManager.GetString("SystemSettingView_TextBlock_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client OPC Address!.
        /// </summary>
        public static string SystemSettingView_TextBlock_07 {
            get {
                return ResourceManager.GetString("SystemSettingView_TextBlock_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-connect clients!.
        /// </summary>
        public static string SystemSettingView_TextBlock_08 {
            get {
                return ResourceManager.GetString("SystemSettingView_TextBlock_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart Configuration!.
        /// </summary>
        public static string SystemSettingView_TextBlock_09 {
            get {
                return ResourceManager.GetString("SystemSettingView_TextBlock_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Address.
        /// </summary>
        public static string SystemSettingView_TextBlock_10 {
            get {
                return ResourceManager.GetString("SystemSettingView_TextBlock_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Time.
        /// </summary>
        public static string SystemSettingView_TextBlock_11 {
            get {
                return ResourceManager.GetString("SystemSettingView_TextBlock_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Language.
        /// </summary>
        public static string SystemSettingView_TextBlock_12 {
            get {
                return ResourceManager.GetString("SystemSettingView_TextBlock_12", resourceCulture);
            }
        }
    }
}
